#155738443 Create layout file for RecyclerView
bibangamba/GitHubUsers pull request #1
Opened 2019-02-21 14:47 UTC by bibangamba

#### What does this PR do?
Adds a recyclerview layout to the project

#### Description of tasks to be done?
* add recyclerview support library to app Gradle dependencies
* add recyclerview layout file and include it in the main_activity layout file

#### How can this be manually tested?
clone the repo and navigate to the branch and check out the layout previews

#### What are the relevant pivotal tracker stories?
#155738443

#### Screenshots
Recyclerview in preview pane
![image](https://user-images.githubusercontent.com/5712103/53177121-7efe3680-3600-11e9-9fc4-4282e94dc3a0.png)

Recyclerview item in preview pane
![image](https://user-images.githubusercontent.com/5712103/53177128-858cae00-3600-11e9-9099-0a213fb1943c.png)

2019-02-22 08:10 UTC, joshNic commented
@bibangamba I have noticed you want to merge directly to master could you please not merge to master but instead create a develop branch

2019-02-22 08:16 UTC, bibangamba commented
going to change this, forgot to change default branch. thank you for the feedback.

2019-02-22 12:00 UTC, joshNic requested changes

2019-02-22 12:00 UTC, joshNic commented on app/src/main/res/layout/github_user_list_item.xml
> +    android:padding="5dp">
@bibangamba  could you please put all the values in the dimens.xml file such that you are only referencing them

2019-02-22 12:44 UTC, bibangamba commented on app/src/main/res/layout/github_user_list_item.xml
> +    android:padding="5dp">
let me do this shortly

2019-02-23 13:15 UTC, bibangamba commented on app/src/main/res/layout/github_user_list_item.xml
> +    android:padding="5dp">
implemented this, thanks for the feedback

2019-02-23 13:16 UTC, bibangamba commented
`note`: the ci build fail is because this branch doesn't have the config yet

2019-02-26 07:00 UTC, joshNic approved these changes
LGTM

2019-02-26 07:02 UTC, merged